name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 8.0
    - name: Run phpunit tests
      uses: php-actions/phpunit@v2
      with:
        php_version: 8.0
