name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 8.0
    - uses: php-actions/phpunit@v2
    - name: Run tests
      run: composer run tests
